import { type ReactNode, useEffect, useMemo, useState } from "react";
import { FeesTable } from "@/components/dashboard/FeesTable";
import type {
  Fee,
  FeeMember,
  FinanceSettings,
  LedgerDateRange,
  LedgerEntry,
  LedgerSummary,
} from "@/components/dashboard/types";
import {
  LEDGER_CATEGORY_OPTIONS,
  formatNumberInput,
  getLedgerCategoryLabel,
  parseNumberInput,
} from "@/lib/finance";

type FinancePanelProps = {
  members: FeeMember[];
  fees: Fee[];
  selectedYear: number;
  onChangeYear: (year: number) => void;
  onToggleFee: (
    member: FeeMember,
    year: number,
    month: number,
    currentPaid: boolean,
    options?: {
      amount?: number;
      createLedgerEntry?: boolean;
    }
  ) => Promise<void>;
  onMarkAllPaid: (
    memberId: number,
    options?: {
      amount?: number;
      createLedgerEntry?: boolean;
    }
  ) => Promise<void>;
  onMarkAllUnpaid: (memberId: number) => Promise<void>;
  financeSettings: FinanceSettings | null;
  financeSettingsLoading: boolean;
  savingFinanceSettings: boolean;
  onSaveFinanceSettings: (settings: FinanceSettings) => Promise<void>;
  onResetLedger: (settings: FinanceSettings) => Promise<void>;
  ledgerEntries: LedgerEntry[];
  ledgerSummary: LedgerSummary | null;
  ledgerLoading: boolean;
  ledgerMonth: number;
  onChangeLedgerMonth: (month: number) => void;
  ledgerDateRange: LedgerDateRange;
  onChangeLedgerDateRange: (range: LedgerDateRange) => void;
  onCreateLedgerEntry: (payload: {
    entryType: "INCOME" | "EXPENSE";
    category: string;
    memberId?: number | null;
    amount: number;
    entryDate: string;
    title: string;
    memo: string;
  }) => Promise<void>;
  onDeleteLedgerEntry: (id: number) => Promise<void>;
  specialFeesPanel: ReactNode;
};

type FinanceViewMode = "MEMBER_FEES" | "LEDGER";

const MONTHS = Array.from({ length: 12 }, (_, index) => index + 1);

function buildMonthDateRange(year: number, month: number) {
  const start = new Date(year, month - 1, 1);
  const end = new Date(year, month, 0);

  const formatLocalDate = (date: Date) => {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");
    return `${y}-${m}-${d}`;
  };

  return {
    startDate: formatLocalDate(start),
    endDate: formatLocalDate(end),
  };
}

const FINANCE_NUMBER_FIELDS: Array<{
  key:
    | "monthlyFeeDefault"
    | "yearlyFeeDefault"
    | "guestFeeDefault"
    | "openingBalance";
  label: string;
}> = [
  { key: "openingBalance", label: "현재 통장 잔액" },
  { key: "monthlyFeeDefault", label: "월회비 기본금액" },
];

function escapeCsvValue(value: string | number | null | undefined) {
  const text = String(value ?? "");
  return `"${text.replace(/"/g, '""')}"`;
}

function downloadLedgerCsv(params: {
  year: number;
  month: number;
  ledgerEntries: LedgerEntry[];
  ledgerSummary: LedgerSummary | null;
  startDate: string;
  endDate: string;
}) {
  const { year, month, ledgerEntries, ledgerSummary, startDate, endDate } =
    params;
  const rows: string[] = [];

  rows.push("\uFEFF" + escapeCsvValue("Ledger Report"));
  rows.push(
    [
      escapeCsvValue("조회 기간"),
      escapeCsvValue(`${startDate} ~ ${endDate}`),
      escapeCsvValue("기준 연월"),
      escapeCsvValue(`${year}년 ${month}월`),
    ].join(",")
  );
  rows.push(
    [
      escapeCsvValue("현재 잔액"),
      escapeCsvValue(ledgerSummary?.currentBalance ?? 0),
      escapeCsvValue("조회 기간 입금"),
      escapeCsvValue(ledgerSummary?.monthlyIncome ?? 0),
      escapeCsvValue("조회 기간 지출"),
      escapeCsvValue(ledgerSummary?.monthlyExpense ?? 0),
    ].join(",")
  );
  rows.push("");
  rows.push(
    ["구분", "날짜", "분류", "내용", "회원", "메모", "금액", "생성방식"]
      .map(escapeCsvValue)
      .join(",")
  );

  ledgerEntries.forEach((entry) => {
    rows.push(
      [
        entry.entryType === "INCOME" ? "입금" : "지출",
        new Date(entry.entryDate).toLocaleDateString("ko-KR"),
        getLedgerCategoryLabel(entry.category),
        entry.title,
        entry.memberName ?? "",
        entry.memo ?? "",
        entry.entryType === "INCOME" ? entry.amount : -entry.amount,
        entry.isAutoGenerated ? "자동 생성" : "수동 등록",
      ]
        .map(escapeCsvValue)
        .join(",")
    );
  });

  const blob = new Blob([rows.join("\r\n")], {
    type: "text/csv;charset=utf-8;",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `ledger-${year}-${String(month).padStart(2, "0")}.csv`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export function FinancePanel({
  members,
  fees,
  selectedYear,
  onChangeYear,
  onToggleFee,
  onMarkAllPaid,
  onMarkAllUnpaid,
  financeSettings,
  financeSettingsLoading,
  savingFinanceSettings,
  onSaveFinanceSettings,
  onResetLedger,
  ledgerEntries,
  ledgerSummary,
  ledgerLoading,
  ledgerMonth,
  onChangeLedgerMonth,
  ledgerDateRange,
  onChangeLedgerDateRange,
  onCreateLedgerEntry,
  onDeleteLedgerEntry,
  specialFeesPanel,
}: FinancePanelProps) {
  const [viewMode, setViewMode] =
    useState<FinanceViewMode>("MEMBER_FEES");
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [entryModalOpen, setEntryModalOpen] = useState(false);
  const [entryType, setEntryType] = useState<"INCOME" | "EXPENSE">(
    "INCOME"
  );
  const [feeModalMember, setFeeModalMember] =
    useState<FeeMember | null>(null);
  const [feeModalYear, setFeeModalYear] = useState<number | null>(null);
  const [feeModalMonth, setFeeModalMonth] = useState<number | null>(null);
  const [financeDraft, setFinanceDraft] = useState<FinanceSettings>({
    ledgerEnabled: false,
    monthlyFeeDefault: 0,
    yearlyFeeDefault: 0,
    guestFeeDefault: 0,
    openingBalance: 0,
  });
  const [feeAmountDraft, setFeeAmountDraft] = useState("0");
  const [feeCreateLedgerDraft, setFeeCreateLedgerDraft] =
    useState(true);
  const [ledgerForm, setLedgerForm] = useState({
    category: "MONTHLY_FEE",
    memberId: "",
    amount: "",
    entryDate: new Date().toISOString().slice(0, 10),
    title: "",
    memo: "",
  });
  const [ledgerPage, setLedgerPage] = useState(1);
  const LEDGER_PAGE_SIZE = 5;
  const ledgerTotalPages = Math.max(1, Math.ceil(ledgerEntries.length / LEDGER_PAGE_SIZE));
  const paginatedLedgerEntries = useMemo(() => {
    const start = (ledgerPage - 1) * LEDGER_PAGE_SIZE;
    return ledgerEntries.slice(start, start + LEDGER_PAGE_SIZE);
  }, [ledgerEntries, ledgerPage]);

  useEffect(() => {
    setLedgerPage(1);
  }, [ledgerEntries.length]);

  const isLedgerEnabled = financeDraft.ledgerEnabled;

  useEffect(() => {
    if (!financeSettings) {
      return;
    }

    setFinanceDraft(financeSettings);
    setFeeCreateLedgerDraft(financeSettings.ledgerEnabled);
  }, [financeSettings]);

  useEffect(() => {
    if (isLedgerEnabled) {
      return;
    }

    setFeeModalMember(null);
    setFeeModalYear(null);
    setFeeModalMonth(null);
    setFeeCreateLedgerDraft(false);
  }, [isLedgerEnabled]);

  useEffect(() => {
    setLedgerForm((current) => ({
      ...current,
      category:
        entryType === "INCOME"
          ? LEDGER_CATEGORY_OPTIONS.income[0].value
          : LEDGER_CATEGORY_OPTIONS.expense[0].value,
      title:
        entryType === "INCOME" ? "기타 입금" : "기타 지출",
    }));
  }, [entryType]);

  const activeCategoryOptions =
    entryType === "INCOME"
      ? LEDGER_CATEGORY_OPTIONS.income
      : LEDGER_CATEGORY_OPTIONS.expense;

  function handleLedgerYearChange(year: number) {
    onChangeYear(year);
    onChangeLedgerDateRange(buildMonthDateRange(year, ledgerMonth));
  }

  function handleLedgerMonthChange(month: number) {
    onChangeLedgerMonth(month);
    onChangeLedgerDateRange(buildMonthDateRange(selectedYear, month));
  }

  function openFeeModal(member: FeeMember, year: number, month: number) {
    setFeeModalMember(member);
    setFeeModalYear(year);
    setFeeModalMonth(month);
    setFeeAmountDraft(
      String(financeSettings?.monthlyFeeDefault ?? 0)
    );
    setFeeCreateLedgerDraft(isLedgerEnabled);
  }

  async function handleFeeToggleRequest(
    member: FeeMember,
    year: number,
    month: number,
    currentPaid: boolean
  ) {
    if (!isLedgerEnabled) {
      await onToggleFee(member, year, month, currentPaid);
      return;
    }

    if (currentPaid) {
      if (
        !confirm(
          `${member.name}님의 ${month}월 월회비를 미납으로 되돌릴까요?\n자동 생성된 장부 입금 기록도 함께 제거됩니다.`
        )
      ) {
        return;
      }

      await onToggleFee(member, year, month, currentPaid, {
        createLedgerEntry: true,
      });
      return;
    }

    openFeeModal(member, year, month);
  }

  async function handleSubmitFeeModal() {
    if (!feeModalMember || feeModalYear === null || feeModalMonth === null) {
      return;
    }

    await onToggleFee(
      feeModalMember,
      feeModalYear,
      feeModalMonth,
      false,
      {
        amount: Number(feeAmountDraft) || 0,
        createLedgerEntry: feeCreateLedgerDraft,
      }
    );

    setFeeModalMember(null);
    setFeeModalYear(null);
    setFeeModalMonth(null);
  }

  function handleCloseSettings() {
    setFinanceDraft(
      financeSettings ?? {
        ledgerEnabled: false,
        monthlyFeeDefault: 0,
        yearlyFeeDefault: 0,
        guestFeeDefault: 0,
        openingBalance: 0,
      }
    );
    setSettingsOpen(false);
  }

  async function handleSaveSettings() {
    const nextSettings = {
      ...financeDraft,
      monthlyFeeDefault: Math.max(
        0,
        Number(financeDraft.monthlyFeeDefault) || 0
      ),
      yearlyFeeDefault: Math.max(
        0,
        Number(financeDraft.yearlyFeeDefault) || 0
      ),
      guestFeeDefault: Math.max(
        0,
        Number(financeDraft.guestFeeDefault) || 0
      ),
      openingBalance: Number(financeDraft.openingBalance) || 0,
    };

    setFinanceDraft(nextSettings);
    await onSaveFinanceSettings(nextSettings);

    setSettingsOpen(false);
  }

  async function handleResetLedger() {
    if (
      !confirm(
        [
          "장부를 다시 시작하시겠어요?",
          "",
          "기존 장부의 입금·지출 내역과 조회 기간 합계가 초기화됩니다.",
          "월/연회비와 수시회비 납부 체크는 그대로 유지됩니다.",
          "이 작업은 되돌릴 수 없습니다.",
        ].join("\n")
      )
    ) {
      return;
    }

    await onResetLedger({
      ...financeDraft,
      monthlyFeeDefault: Math.max(
        0,
        Number(financeDraft.monthlyFeeDefault) || 0
      ),
      yearlyFeeDefault: Math.max(
        0,
        Number(financeDraft.yearlyFeeDefault) || 0
      ),
      guestFeeDefault: Math.max(
        0,
        Number(financeDraft.guestFeeDefault) || 0
      ),
      openingBalance: Number(financeDraft.openingBalance) || 0,
    });

    setSettingsOpen(false);
  }

  async function handleCreateEntry() {
    await onCreateLedgerEntry({
      entryType,
      category: ledgerForm.category,
      memberId: ledgerForm.memberId
        ? Number(ledgerForm.memberId)
        : null,
      amount: Number(ledgerForm.amount) || 0,
      entryDate: ledgerForm.entryDate,
      title: ledgerForm.title.trim(),
      memo: ledgerForm.memo.trim(),
    });

    setEntryModalOpen(false);
    setLedgerForm({
      category:
        entryType === "INCOME"
          ? LEDGER_CATEGORY_OPTIONS.income[0].value
          : LEDGER_CATEGORY_OPTIONS.expense[0].value,
      memberId: "",
      amount: "",
      entryDate: new Date().toISOString().slice(0, 10),
      title: entryType === "INCOME" ? "기타 입금" : "기타 지출",
      memo: "",
    });
  }

  return (
    <div className="space-y-6">
      <div className="rounded-[1.5rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5">
        <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
          <div>
            <h3 className="text-lg font-black text-slate-900">
              장부 관리
            </h3>
            <p className="mt-1 text-sm leading-6 text-slate-500">
              장부 관리가 필요한 클럽은 입금/지출내역과 잔액까지 함께 관리할 수
              있어요.
            </p>
          </div>

          <button
            type="button"
            onClick={() => setSettingsOpen(true)}
            disabled={financeSettingsLoading}
            className="inline-flex h-11 items-center justify-center rounded-2xl border border-slate-200 px-4 text-sm font-bold text-slate-700 transition hover:border-sky-200 hover:bg-sky-50 hover:text-sky-700"
          >
            {financeSettingsLoading ? "설정 불러오는 중..." : "장부 관리 설정"}
          </button>
        </div>
      </div>

      {isLedgerEnabled ? (
        <>
          <div className="grid gap-4 md:grid-cols-3">
            <div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm">
              <p className="text-xs font-bold uppercase tracking-[0.28em] text-slate-400">
                현재 잔액
              </p>
              <p className="mt-3 text-2xl font-black text-slate-900">
                {(ledgerSummary?.currentBalance ?? 0).toLocaleString()}원
              </p>
            </div>
            <div className="rounded-[1.5rem] border border-emerald-100 bg-emerald-50/70 p-5 shadow-sm">
              <p className="text-xs font-bold uppercase tracking-[0.28em] text-emerald-500">
                조회 기간 입금
              </p>
              <p className="mt-3 text-2xl font-black text-emerald-700">
                +{(ledgerSummary?.monthlyIncome ?? 0).toLocaleString()}원
              </p>
            </div>
            <div className="rounded-[1.5rem] border border-rose-100 bg-rose-50/70 p-5 shadow-sm">
              <p className="text-xs font-bold uppercase tracking-[0.28em] text-rose-500">
                조회 기간 지출
              </p>
              <p className="mt-3 text-2xl font-black text-rose-700">
                -{(ledgerSummary?.monthlyExpense ?? 0).toLocaleString()}원
              </p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-2">
            {[
              {
                id: "MEMBER_FEES" as const,
                label: "회원 회비",
                hint: "누가 냈는지 빠르게 체크",
              },
              {
                id: "LEDGER" as const,
                label: "장부",
                hint: "입금과 지출 흐름을 확인",
              },
            ].map((option) => {
              const selected = viewMode === option.id;

              return (
                <button
                  key={option.id}
                  type="button"
                  onClick={() => setViewMode(option.id)}
                  className={`group min-w-0 rounded-[1.25rem] border px-3 py-3 text-left transition md:rounded-[1.5rem] md:px-4 ${
                    selected
                      ? "border-slate-900 bg-slate-900 text-white shadow-[0_18px_35px_rgba(15,23,42,0.18)]"
                      : "border-slate-200 bg-white text-slate-700 hover:border-sky-200 hover:bg-sky-50"
                  }`}
                >
                  <div className="whitespace-nowrap text-[13px] font-black md:text-sm">
                    {option.label}
                  </div>
                  <div
                    className={`mt-1 whitespace-nowrap text-[11px] ${
                      selected
                        ? "text-white/75"
                        : "text-slate-500 group-hover:text-sky-700"
                    } md:text-xs`}
                  >
                    {option.hint}
                  </div>
                </button>
              );
            })}
          </div>
        </>
      ) : (
        <div className="rounded-[1.5rem] border border-dashed border-slate-300 bg-slate-50/70 p-5 text-sm text-slate-600">
          장부 관리 기능은 현재 꺼져 있어요. 지금처럼 납부 체크만
          간단하게 쓰고, 필요할 때만 장부와 잔액 관리를 열 수 있습니다.
        </div>
      )}

      {!isLedgerEnabled || viewMode === "MEMBER_FEES" ? (
        <>
          <FeesTable
            members={members}
            fees={fees}
            selectedYear={selectedYear}
            onChangeYear={onChangeYear}
            onToggleFee={handleFeeToggleRequest}
            onMarkAllPaid={(memberId) =>
              isLedgerEnabled
                ? onMarkAllPaid(memberId, {
                    amount: financeDraft.monthlyFeeDefault ?? 0,
                    createLedgerEntry: true,
                  })
                : onMarkAllPaid(memberId)
            }
            onMarkAllUnpaid={onMarkAllUnpaid}
          />
          {specialFeesPanel}
        </>
      ) : null}

      {isLedgerEnabled && viewMode === "LEDGER" ? (
        <div className="space-y-4">
          <div className="rounded-[1.5rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5">
            <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={() => {
                    setEntryType("INCOME");
                    setEntryModalOpen(true);
                  }}
                  className="rounded-2xl bg-emerald-600 px-4 py-3 text-sm font-black text-white transition hover:bg-emerald-700"
                >
                  입금 등록
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setEntryType("EXPENSE");
                    setEntryModalOpen(true);
                  }}
                  className="rounded-2xl bg-rose-600 px-4 py-3 text-sm font-black text-white transition hover:bg-rose-700"
                >
                  지출 등록
                </button>
              </div>

              <button
                type="button"
                  onClick={() =>
                    downloadLedgerCsv({
                      year: selectedYear,
                      month: ledgerMonth,
                      ledgerEntries,
                      ledgerSummary,
                      startDate: ledgerDateRange.startDate,
                      endDate: ledgerDateRange.endDate,
                    })
                  }
                className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-black text-slate-700 transition hover:border-sky-200 hover:bg-sky-50 hover:text-sky-700"
              >
                엑셀용 CSV 다운로드
              </button>

              <div className="flex min-w-0 flex-col gap-2 md:flex-row md:flex-wrap md:items-center md:justify-end">
                <div className="grid grid-cols-2 gap-2 md:flex md:flex-none">
                  <select
                    value={selectedYear}
                    onChange={(event) =>
                      handleLedgerYearChange(Number(event.target.value))
                    }
                    className="w-full min-w-0 rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                    aria-label="장부 연도 선택"
                  >
                    {Array.from(
                      { length: 7 },
                      (_, index) =>
                        new Date().getFullYear() - 3 + index
                    ).map((year) => (
                      <option key={year} value={year}>
                        {year}년
                      </option>
                    ))}
                  </select>
                  <select
                    value={ledgerMonth}
                    onChange={(event) =>
                      handleLedgerMonthChange(Number(event.target.value))
                    }
                    className="w-full min-w-0 rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                    aria-label="장부 월 선택"
                  >
                    {MONTHS.map((month) => (
                      <option key={month} value={month}>
                        {month}월
                      </option>
                    ))}
                  </select>
                </div>
                <div className="grid grid-cols-2 gap-2 md:flex md:flex-none">
                  <input
                    type="date"
                    value={ledgerDateRange.startDate}
                    onChange={(event) =>
                      onChangeLedgerDateRange({
                        ...ledgerDateRange,
                        startDate: event.target.value,
                      })
                    }
                    className="w-full min-w-0 rounded-2xl border border-slate-200 px-3 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                    aria-label="장부 시작일 선택"
                  />
                  <input
                    type="date"
                    value={ledgerDateRange.endDate}
                    onChange={(event) =>
                      onChangeLedgerDateRange({
                        ...ledgerDateRange,
                        endDate: event.target.value,
                      })
                    }
                    className="w-full min-w-0 rounded-2xl border border-slate-200 px-3 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                    aria-label="장부 종료일 선택"
                  />
                </div>
              </div>
            </div>
          </div>

          <div className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-sm">
            <div className="overflow-x-auto">
              <table className="min-w-[860px] w-full text-sm">
                <thead className="bg-slate-50 text-left text-slate-500">
                  <tr>
                    <th className="px-4 py-4 font-semibold">구분</th>
                    <th className="px-4 py-4 font-semibold">날짜</th>
                    <th className="px-4 py-4 font-semibold">항목</th>
                    <th className="px-4 py-4 font-semibold">분류</th>
                    <th className="px-4 py-4 font-semibold">메모</th>
                    <th className="px-4 py-4 text-right font-semibold">금액</th>
                    <th className="px-4 py-4 text-right font-semibold">관리</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {paginatedLedgerEntries.map((entry) => (
                    <tr key={entry.id} className="hover:bg-slate-50">
                      <td className="px-4 py-4">
                        <span
                          className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${
                            entry.entryType === "INCOME"
                              ? "bg-emerald-50 text-emerald-700"
                              : "bg-rose-50 text-rose-700"
                          }`}
                        >
                          {entry.entryType === "INCOME" ? "입금" : "지출"}
                        </span>
                      </td>
                      <td className="px-4 py-4 text-slate-600">
                        {new Date(entry.entryDate).toLocaleDateString("ko-KR")}
                      </td>
                      <td className="px-4 py-4">
                        <div className="font-bold text-slate-900">
                          {entry.title}
                        </div>
                        <div className="mt-1 text-xs text-slate-400">
                          {entry.isAutoGenerated ? "자동 생성" : "수동 등록"}
                          {entry.memberName ? ` · ${entry.memberName}` : ""}
                        </div>
                      </td>
                      <td className="px-4 py-4 text-slate-600">
                        {getLedgerCategoryLabel(entry.category)}
                      </td>
                      <td className="px-4 py-4 text-slate-500">
                        {entry.memo || "-"}
                      </td>
                      <td
                        className={`px-4 py-4 text-right font-black ${
                          entry.entryType === "INCOME"
                            ? "text-emerald-700"
                            : "text-rose-700"
                        }`}
                      >
                        {entry.entryType === "INCOME" ? "+" : "-"}
                        {entry.amount.toLocaleString()}원
                      </td>
                      <td className="px-4 py-4 text-right">
                        {!entry.isAutoGenerated ? (
                          <button
                            type="button"
                            onClick={() => {
                              if (
                                !confirm("이 장부 내역을 삭제하시겠어요?")
                              ) {
                                return;
                              }

                              onDeleteLedgerEntry(entry.id).catch(
                                (error: Error) => {
                                  alert(error.message);
                                }
                              );
                            }}
                            className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600 transition hover:bg-slate-200"
                          >
                            삭제
                          </button>
                        ) : (
                          <span className="text-xs text-slate-400">자동</span>
                        )}
                      </td>
                    </tr>
                  ))}

                  {ledgerEntries.length === 0 ? (
                    <tr>
                      <td
                        colSpan={7}
                        className="px-4 py-12 text-center text-sm text-slate-400"
                      >
                        {ledgerLoading
                          ? "장부 내역을 불러오는 중입니다."
                          : "선택한 기간의 장부 내역이 없습니다."}
                      </td>
                    </tr>
                  ) : null}
                </tbody>
              </table>
            </div>
            {ledgerTotalPages > 1 && (
              <div className="flex items-center justify-between border-t border-slate-100 px-4 py-3">
                <span className="text-xs text-slate-400">
                  {ledgerEntries.length}건 중 {(ledgerPage - 1) * LEDGER_PAGE_SIZE + 1}–{Math.min(ledgerPage * LEDGER_PAGE_SIZE, ledgerEntries.length)}건
                </span>
                <div className="flex items-center gap-1">
                  <button
                    onClick={() => setLedgerPage((p) => Math.max(1, p - 1))}
                    disabled={ledgerPage === 1}
                    className="rounded-xl border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-600 transition hover:bg-slate-50 disabled:opacity-30"
                  >
                    이전
                  </button>
                  {Array.from({ length: ledgerTotalPages }, (_, i) => i + 1).map((p) => (
                    <button
                      key={p}
                      onClick={() => setLedgerPage(p)}
                      className={`rounded-xl px-3 py-1.5 text-xs font-bold transition ${
                        p === ledgerPage
                          ? "bg-slate-900 text-white"
                          : "border border-slate-200 text-slate-600 hover:bg-slate-50"
                      }`}
                    >
                      {p}
                    </button>
                  ))}
                  <button
                    onClick={() => setLedgerPage((p) => Math.min(ledgerTotalPages, p + 1))}
                    disabled={ledgerPage === ledgerTotalPages}
                    className="rounded-xl border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-600 transition hover:bg-slate-50 disabled:opacity-30"
                  >
                    다음
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      ) : null}

      {settingsOpen ? (
        <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/45 px-4 py-6">
          <div className="w-full max-w-xl rounded-[2rem] border border-white/70 bg-white p-6 shadow-[0_24px_80px_rgba(15,23,42,0.24)]">
            <div className="flex items-start justify-between gap-4">
              <div>
                <h4 className="text-xl font-black text-slate-900">
                  장부 관리 설정
                </h4>
                <p className="mt-2 text-sm leading-6 text-slate-500">
                  현재 통장 잔액과 월회비 기본금액만 입력하고 오늘부터 새로 관리하는 방식으로
                  사용하는 걸 추천해요. 과거 회비를 다시 체크할 예정이라면
                  그 금액을 초기 잔액에 중복해서 넣지 마세요.
                </p>
              </div>
            </div>

            <div className="mt-6 space-y-4">
              <label className="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 px-4 py-4">
                  <span className="text-sm font-bold text-slate-700">
                    장부 관리 사용
                  </span>
                <input
                  type="checkbox"
                  checked={financeDraft.ledgerEnabled}
                  onChange={(event) =>
                    setFinanceDraft((current) => ({
                      ...current,
                      ledgerEnabled: event.target.checked,
                    }))
                  }
                  className="h-5 w-5 rounded border-slate-300"
                />
              </label>

              <div className="grid gap-4 md:grid-cols-2">
                {FINANCE_NUMBER_FIELDS.map(({ label, key }) => (
                  <label
                    key={key}
                    className="space-y-2 rounded-2xl border border-slate-200 bg-white px-4 py-4"
                  >
                    <span className="text-sm font-bold text-slate-700">
                      {label}
                    </span>
                    <input
                      type="text"
                      inputMode="numeric"
                      value={formatNumberInput(financeDraft[key])}
                      onChange={(event) =>
                        setFinanceDraft((current) => ({
                          ...current,
                          [key]: parseNumberInput(event.target.value),
                        }))
                      }
                      className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                    />
                    {key === "openingBalance" ? (
                      <p className="text-xs leading-5 text-slate-400">
                        장부를 시작하는 시점의 실제 통장 잔액만 입력해 주세요.
                        과거 회비를 다시 체크할 예정이라면 그 금액은 포함하지
                        않는 것이 맞습니다.
                      </p>
                    ) : null}
                  </label>
                ))}
              </div>
            </div>

            <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              {financeDraft.ledgerEnabled ? (
                <button
                  type="button"
                  onClick={() => {
                    handleResetLedger().catch((error: Error) => {
                      alert(error.message);
                    });
                  }}
                  className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-black text-rose-700 transition hover:bg-rose-100"
                >
                  장부 다시 시작
                </button>
              ) : (
                <span />
              )}

              <div className="flex justify-end gap-2">
                <button
                  type="button"
                  onClick={handleCloseSettings}
                  className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-600 transition hover:bg-slate-50"
                >
                  취소
              </button>
              <button
                type="button"
                onClick={() => {
                  handleSaveSettings().catch((error: Error) => {
                    alert(error.message);
                  });
                }}
                disabled={savingFinanceSettings}
                className="rounded-2xl bg-slate-900 px-4 py-3 text-sm font-black text-white transition hover:bg-slate-800 disabled:opacity-60"
              >
                {savingFinanceSettings ? "저장 중..." : "저장"}
              </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}

      {feeModalMember && feeModalYear !== null && feeModalMonth !== null ? (
        <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/45 px-4 py-6">
          <div className="w-full max-w-md rounded-[2rem] border border-white/70 bg-white p-6 shadow-[0_24px_80px_rgba(15,23,42,0.24)]">
            <h4 className="text-xl font-black text-slate-900">
              월회비 납부 처리
            </h4>
            <p className="mt-2 text-sm leading-6 text-slate-500">
              체크만 해도 장부 입금과 잔액 반영까지 함께 처리할 수 있어요.
            </p>

            <div className="mt-6 space-y-4">
              <div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-4 text-sm text-slate-600">
                <div className="font-bold text-slate-900">{feeModalMember.name}</div>
                <div className="mt-1">
                  {feeModalYear}년 {feeModalMonth}월 월회비
                </div>
              </div>

              <label className="space-y-2">
                <span className="text-sm font-bold text-slate-700">금액</span>
                <input
                  type="text"
                  inputMode="numeric"
                  value={formatNumberInput(feeAmountDraft)}
                  onChange={(event) =>
                    setFeeAmountDraft(
                      String(parseNumberInput(event.target.value))
                    )
                  }
                  className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                />
              </label>

              <label className="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 px-4 py-4">
                <span className="text-sm font-bold text-slate-700">
                  장부에 입금 기록도 함께 생성
                </span>
                <input
                  type="checkbox"
                  checked={feeCreateLedgerDraft}
                  onChange={(event) =>
                    setFeeCreateLedgerDraft(event.target.checked)
                  }
                  className="h-5 w-5 rounded border-slate-300"
                />
              </label>
            </div>

            <div className="mt-6 flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setFeeModalMember(null)}
                className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-600 transition hover:bg-slate-50"
              >
                취소
              </button>
              <button
                type="button"
                onClick={() => {
                  handleSubmitFeeModal().catch((error: Error) => {
                    alert(error.message);
                  });
                }}
                className="rounded-2xl bg-slate-900 px-4 py-3 text-sm font-black text-white transition hover:bg-slate-800"
              >
                저장
              </button>
            </div>
          </div>
        </div>
      ) : null}

      {entryModalOpen ? (
        <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/45 px-4 py-6">
          <div className="w-full max-w-lg rounded-[2rem] border border-white/70 bg-white p-6 shadow-[0_24px_80px_rgba(15,23,42,0.24)]">
            <h4 className="text-xl font-black text-slate-900">
              {entryType === "INCOME" ? "입금 등록" : "지출 등록"}
            </h4>
            <p className="mt-2 text-sm leading-6 text-slate-500">
              평소 사용하는 사소한 지출까지 장부에 적어두면 잔액이 훨씬
              정확해집니다.
            </p>

            <div className="mt-6 grid gap-4 md:grid-cols-2">
              <label className="space-y-2 md:col-span-1">
                <span className="text-sm font-bold text-slate-700">날짜</span>
                <input
                  type="date"
                  value={ledgerForm.entryDate}
                  onChange={(event) =>
                    setLedgerForm((current) => ({
                      ...current,
                      entryDate: event.target.value,
                    }))
                  }
                  className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                />
              </label>

              <label className="space-y-2 md:col-span-1">
                <span className="text-sm font-bold text-slate-700">금액</span>
                <input
                  type="text"
                  inputMode="numeric"
                  value={formatNumberInput(ledgerForm.amount)}
                  onChange={(event) =>
                    setLedgerForm((current) => ({
                      ...current,
                      amount: String(
                        parseNumberInput(event.target.value)
                      ),
                    }))
                  }
                  className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                />
              </label>

              <label className="space-y-2 md:col-span-1">
                <span className="text-sm font-bold text-slate-700">분류</span>
                <select
                  value={ledgerForm.category}
                  onChange={(event) =>
                    setLedgerForm((current) => ({
                      ...current,
                      category: event.target.value,
                    }))
                  }
                  className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                >
                  {activeCategoryOptions.map((option) => (
                    <option key={option.value} value={option.value}>
                      {option.label}
                    </option>
                  ))}
                </select>
              </label>

              <label className="space-y-2 md:col-span-1">
                <span className="text-sm font-bold text-slate-700">
                  회원 연결 (선택)
                </span>
                <select
                  value={ledgerForm.memberId}
                  onChange={(event) =>
                    setLedgerForm((current) => ({
                      ...current,
                      memberId: event.target.value,
                    }))
                  }
                  className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                >
                  <option value="">선택 안 함</option>
                  {members.map((member) => (
                    <option key={member.id} value={member.id}>
                      {member.name}
                    </option>
                  ))}
                </select>
              </label>

              <label className="space-y-2 md:col-span-2">
                <span className="text-sm font-bold text-slate-700">내용</span>
                <input
                  type="text"
                  value={ledgerForm.title}
                  onChange={(event) =>
                    setLedgerForm((current) => ({
                      ...current,
                      title: event.target.value,
                    }))
                  }
                  className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                />
              </label>

              <label className="space-y-2 md:col-span-2">
                <span className="text-sm font-bold text-slate-700">메모</span>
                <textarea
                  value={ledgerForm.memo}
                  onChange={(event) =>
                    setLedgerForm((current) => ({
                      ...current,
                      memo: event.target.value,
                    }))
                  }
                  rows={3}
                  className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none transition focus:border-sky-400"
                />
              </label>
            </div>

            <div className="mt-6 flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setEntryModalOpen(false)}
                className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-600 transition hover:bg-slate-50"
              >
                취소
              </button>
              <button
                type="button"
                onClick={() => {
                  handleCreateEntry().catch((error: Error) => {
                    alert(error.message);
                  });
                }}
                className="rounded-2xl bg-slate-900 px-4 py-3 text-sm font-black text-white transition hover:bg-slate-800"
              >
                저장
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}
