import {
  notFoundResponse,
  requireAuthAdmin,
  unauthorizedResponse,
} from "@/lib/api-auth";
import {
  buildMonthlyFeeReferenceKey,
  buildMonthlyFeeTitle,
} from "@/lib/finance";
import { ensureFinanceSchema } from "@/lib/finance-schema";
import { prisma } from "@/lib/prisma";
import { sendTelegramAlert } from "@/lib/telegram";
import { NextResponse } from "next/server";

const feeSelect = {
  id: true,
  memberId: true,
  year: true,
  month: true,
  paid: true,
} as const;

type FeeRow = {
  id: number;
  memberId: number;
  year: number;
  month: number;
  paid: boolean;
};

type MemberRow = {
  id: number;
  name: string;
};

async function getValidMember(memberId: number, clubId: number) {
  const rows = await prisma.$queryRaw<MemberRow[]>`
    SELECT "id", "name"
    FROM "Member"
    WHERE "id" = ${memberId}
      AND "clubId" = ${clubId}
      AND "deleted" = false
  `;

  return rows[0] ?? null;
}

export async function GET(req: Request) {
  try {
    const admin = await requireAuthAdmin();
    if (!admin) return unauthorizedResponse();

    const { searchParams } = new URL(req.url);
    const year = Number(searchParams.get("year"));

    if (!Number.isFinite(year)) {
      return NextResponse.json(
        { error: "연도를 올바르게 입력해 주세요." },
        { status: 400 }
      );
    }

    const fees = await prisma.fee.findMany({
      where: {
        year,
        paid: true,
        member: {
          clubId: admin.clubId,
          deleted: false,
        },
      },
      select: feeSelect,
    });

    return NextResponse.json(fees);
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "회비 목록을 불러오지 못했습니다." },
      { status: 500 }
    );
  }
}

export async function POST(req: Request) {
  try {
    const admin = await requireAuthAdmin();
    if (!admin) return unauthorizedResponse();
    await ensureFinanceSchema();

    const body = await req.json();
    const memberId = Number(body.memberId);
    const year = Number(body.year);
    const month = Number(body.month);
    const paid = Boolean(body.paid);
    const amount = Math.max(0, Number(body.amount) || 0);
    const createLedgerEntry = Boolean(body.createLedgerEntry);

    if (!Number.isFinite(memberId) || !Number.isFinite(year) || !Number.isFinite(month)) {
      return NextResponse.json(
        { error: "필수 데이터가 누락되었습니다." },
        { status: 400 }
      );
    }

    const member = await getValidMember(memberId, admin.clubId);
    if (!member) {
      return notFoundResponse("회비를 수정할 회원을 찾을 수 없습니다.");
    }

    const club = await prisma.club.findUnique({
      where: { id: admin.clubId },
      select: { name: true },
    });
    const clubName = club?.name ?? String(admin.clubId);
    const referenceKey = buildMonthlyFeeReferenceKey(
      admin.clubId,
      member.id,
      year,
      month
    );

    if (!paid) {
      await prisma.$transaction([
        prisma.$executeRaw`
          DELETE FROM "Fee"
          WHERE "memberId" = ${member.id}
            AND "year" = ${year}
            AND "month" = ${month}
        `,
        prisma.$executeRaw`
          DELETE FROM "LedgerEntry"
          WHERE "clubId" = ${admin.clubId}
            AND "referenceKey" = ${referenceKey}
            AND "isAutoGenerated" = true
        `,
      ]);

      void sendTelegramAlert({
        event: "MONTHLY_FEE_TOGGLE",
        clubName,
        memberName: member.name,
        year,
        month,
        paid: false,
      });

      return NextResponse.json({
        id: 0,
        memberId: member.id,
        year,
        month,
        paid: false,
      });
    }

    const fees = await prisma.$queryRaw<FeeRow[]>`
      WITH upserted AS (
        INSERT INTO "Fee" ("memberId", "year", "month", "paid")
        VALUES (${member.id}, ${year}, ${month}, true)
        ON CONFLICT ("memberId", "year", "month")
        DO UPDATE SET "paid" = EXCLUDED."paid"
        RETURNING "id", "memberId", "year", "month", "paid"
      )
      SELECT "id", "memberId", "year", "month", "paid"
      FROM upserted
    `;

    const fee = fees[0];
    if (!fee) {
      return notFoundResponse("회비를 수정할 회원을 찾을 수 없습니다.");
    }

    if (createLedgerEntry && amount > 0) {
      await prisma.$executeRaw`
        INSERT INTO "LedgerEntry" (
          "clubId",
          "memberId",
          "entryType",
          "sourceType",
          "category",
          "amount",
          "entryDate",
          "title",
          "memo",
          "isAutoGenerated",
          "referenceKey",
          "createdByAdminId",
          "updatedAt"
        )
        VALUES (
          ${admin.clubId},
          ${member.id},
          'INCOME',
          'AUTO_FEE',
          'MONTHLY_FEE',
          ${amount},
          CURRENT_TIMESTAMP,
          ${buildMonthlyFeeTitle(member.name, year, month)},
          '',
          true,
          ${referenceKey},
          ${admin.adminId},
          CURRENT_TIMESTAMP
        )
        ON CONFLICT ("referenceKey")
        DO UPDATE SET
          "amount" = EXCLUDED."amount",
          "title" = EXCLUDED."title",
          "updatedAt" = CURRENT_TIMESTAMP
      `;
    }

    void sendTelegramAlert({
      event: "MONTHLY_FEE_TOGGLE",
      clubName,
      memberName: member.name,
      year,
      month,
      paid: true,
    });

    return NextResponse.json(fee);
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "회비 상태를 저장하지 못했습니다." },
      { status: 500 }
    );
  }
}

export async function PUT(req: Request) {
  try {
    const admin = await requireAuthAdmin();
    if (!admin) return unauthorizedResponse();
    await ensureFinanceSchema();

    const body = await req.json();
    const memberId = Number(body.memberId);
    const year = Number(body.year);
    const paid = Boolean(body.paid);
    const amount = Math.max(0, Number(body.amount) || 0);
    const createLedgerEntry = Boolean(body.createLedgerEntry);

    if (!Number.isFinite(memberId) || !Number.isFinite(year)) {
      return NextResponse.json(
        { error: "회원과 연도 정보가 필요합니다." },
        { status: 400 }
      );
    }

    const member = await getValidMember(memberId, admin.clubId);
    if (!member) {
      return notFoundResponse("회비를 수정할 회원을 찾을 수 없습니다.");
    }

    const club = await prisma.club.findUnique({
      where: { id: admin.clubId },
      select: { name: true },
    });
    const clubName = club?.name ?? String(admin.clubId);

    if (!paid) {
      await prisma.$transaction([
        prisma.$executeRaw`
          DELETE FROM "Fee"
          WHERE "memberId" = ${member.id}
            AND "year" = ${year}
        `,
        prisma.$executeRaw`
          DELETE FROM "LedgerEntry"
          WHERE "clubId" = ${admin.clubId}
            AND "referenceKey" LIKE ${`MONTHLY_FEE:${admin.clubId}:${member.id}:${year}:%`}
            AND "isAutoGenerated" = true
        `,
      ]);

      void sendTelegramAlert({
        event: "YEARLY_FEE_TOGGLE",
        clubName,
        memberName: member.name,
        year,
        paid: false,
      });

      return NextResponse.json([]);
    }

    const fees = await prisma.$queryRaw<FeeRow[]>`
      WITH upserted AS (
        INSERT INTO "Fee" ("memberId", "year", "month", "paid")
        SELECT ${member.id}, ${year}, gs.month, true
        FROM generate_series(1, 12) AS gs(month)
        ON CONFLICT ("memberId", "year", "month")
        DO UPDATE SET "paid" = EXCLUDED."paid"
        RETURNING "id", "memberId", "year", "month", "paid"
      )
      SELECT "id", "memberId", "year", "month", "paid"
      FROM upserted
      ORDER BY "month" ASC
    `;

    if (fees.length === 0) {
      return notFoundResponse("회비를 수정할 회원을 찾을 수 없습니다.");
    }

    if (createLedgerEntry && amount > 0) {
      for (const fee of fees) {
        const referenceKey = buildMonthlyFeeReferenceKey(
          admin.clubId,
          member.id,
          year,
          fee.month
        );

        await prisma.$executeRaw`
          INSERT INTO "LedgerEntry" (
            "clubId",
            "memberId",
            "entryType",
            "sourceType",
            "category",
            "amount",
            "entryDate",
            "title",
            "memo",
            "isAutoGenerated",
            "referenceKey",
            "createdByAdminId",
            "updatedAt"
          )
          VALUES (
            ${admin.clubId},
            ${member.id},
            'INCOME',
            'AUTO_FEE',
            'MONTHLY_FEE',
            ${amount},
            CURRENT_TIMESTAMP,
            ${buildMonthlyFeeTitle(member.name, year, fee.month)},
            '',
            true,
            ${referenceKey},
            ${admin.adminId},
            CURRENT_TIMESTAMP
          )
          ON CONFLICT ("referenceKey")
          DO UPDATE SET
            "amount" = EXCLUDED."amount",
            "title" = EXCLUDED."title",
            "updatedAt" = CURRENT_TIMESTAMP
        `;
      }
    }

    void sendTelegramAlert({
      event: "YEARLY_FEE_TOGGLE",
      clubName,
      memberName: member.name,
      year,
      paid: true,
    });

    return NextResponse.json(fees);
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "회비 일괄 처리에 실패했습니다." },
      { status: 500 }
    );
  }
}
