import {
  requireAuthAdmin,
  unauthorizedResponse,
} from "@/lib/api-auth";
import { getLedgerCategoryLabel, getMonthRange } from "@/lib/finance";
import { ensureFinanceSchema } from "@/lib/finance-schema";
import { prisma } from "@/lib/prisma";
import { sendTelegramAlert } from "@/lib/telegram";
import { NextResponse } from "next/server";

type LedgerEntryRow = {
  id: number;
  clubId: number;
  entryType: "INCOME" | "EXPENSE";
  sourceType:
    | "AUTO_FEE"
    | "MANUAL_INCOME"
    | "MANUAL_EXPENSE"
    | "OPENING_BALANCE";
  category: string;
  memberId: number | null;
  memberName: string | null;
  amount: number;
  entryDate: Date;
  title: string;
  memo: string;
  isAutoGenerated: boolean;
  referenceKey: string | null;
  createdAt: Date;
};

type SummaryRow = {
  openingBalance: number;
  currentBalance: number;
  monthlyIncome: number;
  monthlyExpense: number;
};

async function getLedgerPayload(clubId: number, year: number, month: number) {
  await ensureFinanceSchema();

  const { start, end } = getMonthRange(year, month);

  const [entries, summaryRows] = await Promise.all([
    prisma.$queryRaw<LedgerEntryRow[]>`
      SELECT
        ledger."id",
        ledger."clubId",
        ledger."entryType",
        ledger."sourceType",
        ledger."category",
        ledger."memberId",
        member."name" AS "memberName",
        ledger."amount",
        ledger."entryDate",
        ledger."title",
        ledger."memo",
        ledger."isAutoGenerated",
        ledger."referenceKey",
        ledger."createdAt"
      FROM "LedgerEntry" AS ledger
      LEFT JOIN "Member" AS member
        ON member."id" = ledger."memberId"
      WHERE ledger."clubId" = ${clubId}
        AND ledger."entryDate" >= ${start}
        AND ledger."entryDate" < ${end}
      ORDER BY ledger."entryDate" DESC, ledger."id" DESC
    `,
    prisma.$queryRaw<SummaryRow[]>`
      SELECT
        settings."openingBalance",
        settings."openingBalance"
          + COALESCE(SUM(
              CASE
                WHEN ledger."entryType" = 'INCOME' THEN ledger."amount"
                ELSE -ledger."amount"
              END
            ), 0) AS "currentBalance",
        COALESCE(SUM(
          CASE
            WHEN ledger."entryType" = 'INCOME'
              AND ledger."entryDate" >= ${start}
              AND ledger."entryDate" < ${end}
            THEN ledger."amount"
            ELSE 0
          END
        ), 0) AS "monthlyIncome",
        COALESCE(SUM(
          CASE
            WHEN ledger."entryType" = 'EXPENSE'
              AND ledger."entryDate" >= ${start}
              AND ledger."entryDate" < ${end}
            THEN ledger."amount"
            ELSE 0
          END
        ), 0) AS "monthlyExpense"
      FROM "ClubFinanceSettings" AS settings
      LEFT JOIN "LedgerEntry" AS ledger
        ON ledger."clubId" = settings."clubId"
      WHERE settings."clubId" = ${clubId}
      GROUP BY settings."openingBalance"
    `,
  ]);

  const summary = summaryRows[0] ?? {
    openingBalance: 0,
    currentBalance: 0,
    monthlyIncome: 0,
    monthlyExpense: 0,
  };

  return {
    entries,
    summary: {
      currentBalance: Number(summary.currentBalance) || 0,
      monthlyIncome: Number(summary.monthlyIncome) || 0,
      monthlyExpense: Number(summary.monthlyExpense) || 0,
    },
  };
}

export async function GET(req: Request) {
  try {
    const admin = await requireAuthAdmin();
    if (!admin) {
      return unauthorizedResponse();
    }

    const { searchParams } = new URL(req.url);
    const year =
      Number(searchParams.get("year")) || new Date().getFullYear();
    const month =
      Number(searchParams.get("month")) || new Date().getMonth() + 1;
    const startDateParam = searchParams.get("startDate");
    const endDateParam = searchParams.get("endDate");

    if (startDateParam && endDateParam) {
      await ensureFinanceSchema();

      const start = new Date(startDateParam);
      const end = new Date(endDateParam);
      end.setHours(23, 59, 59, 999);

      if (
        Number.isNaN(start.getTime()) ||
        Number.isNaN(end.getTime()) ||
        start > end
      ) {
        return NextResponse.json(
          { error: "조회 기간을 다시 확인해 주세요." },
          { status: 400 }
        );
      }

      const [entries, summaryRows] = await Promise.all([
        prisma.$queryRaw<LedgerEntryRow[]>`
          SELECT
            ledger."id",
            ledger."clubId",
            ledger."entryType",
            ledger."sourceType",
            ledger."category",
            ledger."memberId",
            member."name" AS "memberName",
            ledger."amount",
            ledger."entryDate",
            ledger."title",
            ledger."memo",
            ledger."isAutoGenerated",
            ledger."referenceKey",
            ledger."createdAt"
          FROM "LedgerEntry" AS ledger
          LEFT JOIN "Member" AS member
            ON member."id" = ledger."memberId"
          WHERE ledger."clubId" = ${admin.clubId}
            AND ledger."entryDate" >= ${start}
            AND ledger."entryDate" <= ${end}
          ORDER BY ledger."entryDate" DESC, ledger."id" DESC
        `,
        prisma.$queryRaw<SummaryRow[]>`
          SELECT
            settings."openingBalance",
            settings."openingBalance"
              + COALESCE(SUM(
                  CASE
                    WHEN ledger."entryType" = 'INCOME' THEN ledger."amount"
                    ELSE -ledger."amount"
                  END
                ), 0) AS "currentBalance",
            COALESCE(SUM(
              CASE
                WHEN ledger."entryType" = 'INCOME'
                  AND ledger."entryDate" >= ${start}
                  AND ledger."entryDate" <= ${end}
                THEN ledger."amount"
                ELSE 0
              END
            ), 0) AS "monthlyIncome",
            COALESCE(SUM(
              CASE
                WHEN ledger."entryType" = 'EXPENSE'
                  AND ledger."entryDate" >= ${start}
                  AND ledger."entryDate" <= ${end}
                THEN ledger."amount"
                ELSE 0
              END
            ), 0) AS "monthlyExpense"
          FROM "ClubFinanceSettings" AS settings
          LEFT JOIN "LedgerEntry" AS ledger
            ON ledger."clubId" = settings."clubId"
          WHERE settings."clubId" = ${admin.clubId}
          GROUP BY settings."openingBalance"
        `,
      ]);

      const summary = summaryRows[0] ?? {
        openingBalance: 0,
        currentBalance: 0,
        monthlyIncome: 0,
        monthlyExpense: 0,
      };

      return NextResponse.json({
        entries,
        summary: {
          currentBalance: Number(summary.currentBalance) || 0,
          monthlyIncome: Number(summary.monthlyIncome) || 0,
          monthlyExpense: Number(summary.monthlyExpense) || 0,
        },
      });
    }

    return NextResponse.json(
      await getLedgerPayload(admin.clubId, year, month)
    );
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "장부 내역을 불러오지 못했습니다." },
      { status: 500 }
    );
  }
}

export async function POST(req: Request) {
  try {
    const admin = await requireAuthAdmin();
    if (!admin) {
      return unauthorizedResponse();
    }

    await ensureFinanceSchema();

    const body = await req.json();
    const entryType = body.entryType === "EXPENSE" ? "EXPENSE" : "INCOME";
    const category = String(body.category ?? "").trim();
    const amount = Math.max(0, Number(body.amount) || 0);
    const title = String(body.title ?? "").trim();
    const memo = String(body.memo ?? "").trim();
    const memberId =
      body.memberId === null || body.memberId === undefined || body.memberId === ""
        ? null
        : Number(body.memberId);
    const entryDate = body.entryDate
      ? new Date(body.entryDate)
      : new Date();

    if (!category || !amount || !title || Number.isNaN(entryDate.getTime())) {
      return NextResponse.json(
        { error: "장부 등록 항목을 다시 확인해주세요." },
        { status: 400 }
      );
    }

    const rows = await prisma.$queryRaw<LedgerEntryRow[]>`
      INSERT INTO "LedgerEntry" (
        "clubId",
        "memberId",
        "entryType",
        "sourceType",
        "category",
        "amount",
        "entryDate",
        "title",
        "memo",
        "isAutoGenerated",
        "createdByAdminId",
        "updatedAt"
      )
      VALUES (
        ${admin.clubId},
        ${memberId},
        ${entryType},
        ${entryType === "INCOME" ? "MANUAL_INCOME" : "MANUAL_EXPENSE"},
        ${category},
        ${amount},
        ${entryDate},
        ${title},
        ${memo},
        false,
        ${admin.adminId},
        CURRENT_TIMESTAMP
      )
      RETURNING
        "id",
        "clubId",
        "entryType",
        "sourceType",
        "category",
        "memberId",
        NULL::TEXT AS "memberName",
        "amount",
        "entryDate",
        "title",
        "memo",
        "isAutoGenerated",
        "referenceKey",
        "createdAt"
    `;

    const [club, member] = await Promise.all([
      prisma.club.findUnique({
        where: { id: admin.clubId },
        select: { name: true },
      }),
      memberId
        ? prisma.member.findUnique({
            where: { id: memberId },
            select: { name: true },
          })
        : Promise.resolve(null),
    ]);

    void sendTelegramAlert({
      event:
        entryType === "INCOME"
          ? "LEDGER_MANUAL_INCOME_CREATE"
          : "LEDGER_MANUAL_EXPENSE_CREATE",
      clubName: club?.name ?? String(admin.clubId),
      title,
      category: getLedgerCategoryLabel(category),
      amount,
      memberName: member?.name ?? null,
    });

    return NextResponse.json(rows[0]);
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "장부 내역을 저장하지 못했습니다." },
      { status: 500 }
    );
  }
}

export async function DELETE(req: Request) {
  try {
    const admin = await requireAuthAdmin();
    if (!admin) {
      return unauthorizedResponse();
    }

    await ensureFinanceSchema();

    const { id } = await req.json();
    const ledgerId = Number(id);

    if (!Number.isFinite(ledgerId)) {
      return NextResponse.json(
        { error: "삭제할 장부 내역을 확인해주세요." },
        { status: 400 }
      );
    }

    await prisma.$executeRaw`
      DELETE FROM "LedgerEntry"
      WHERE "id" = ${ledgerId}
        AND "clubId" = ${admin.clubId}
        AND "isAutoGenerated" = false
    `;

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "장부 내역을 삭제하지 못했습니다." },
      { status: 500 }
    );
  }
}

