import { prisma } from "@/lib/prisma";

let ensured = false;

export async function ensureFinanceSchema() {
  if (ensured) {
    return;
  }

  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS "ClubFinanceSettings" (
      "clubId" INTEGER PRIMARY KEY REFERENCES "Club"("id") ON DELETE CASCADE,
      "ledgerEnabled" BOOLEAN NOT NULL DEFAULT false,
      "monthlyFeeDefault" INTEGER NOT NULL DEFAULT 0,
      "yearlyFeeDefault" INTEGER NOT NULL DEFAULT 0,
      "guestFeeDefault" INTEGER NOT NULL DEFAULT 0,
      "openingBalance" INTEGER NOT NULL DEFAULT 0,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS "LedgerEntry" (
      "id" SERIAL PRIMARY KEY,
      "clubId" INTEGER NOT NULL REFERENCES "Club"("id") ON DELETE CASCADE,
      "memberId" INTEGER REFERENCES "Member"("id") ON DELETE SET NULL,
      "entryType" TEXT NOT NULL,
      "sourceType" TEXT NOT NULL,
      "category" TEXT NOT NULL,
      "amount" INTEGER NOT NULL,
      "entryDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "title" TEXT NOT NULL DEFAULT '',
      "memo" TEXT NOT NULL DEFAULT '',
      "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
      "referenceKey" TEXT UNIQUE,
      "createdByAdminId" INTEGER REFERENCES "Admin"("id") ON DELETE SET NULL,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await prisma.$executeRawUnsafe(`
    CREATE INDEX IF NOT EXISTS "LedgerEntry_clubId_entryDate_idx"
    ON "LedgerEntry" ("clubId", "entryDate" DESC)
  `);

  await prisma.$executeRawUnsafe(`
    INSERT INTO "ClubFinanceSettings" ("clubId")
    SELECT "id" FROM "Club"
    ON CONFLICT ("clubId") DO NOTHING
  `);

  ensured = true;
}
